#!/bin/sh
#
export QPSMTPD_CONFIG=/etc/qpsmtpd
QPUSER=qpsmtpd
# limit qpsmtpd to 300MB memory
MAXRAM=300000000
BIN=/usr/bin
PERL=/usr/bin/perl
IP=0.0.0.0
LANG=C

# See also: http://wiki.qpsmtpd.org/deploy:start

exec 2>&1 \
sh -c "
  exec $BIN/softlimit -m $MAXRAM   \
    $PERL -T /usr/bin/qpsmtpd-forkserver  \
      --listen-address $IP         \
      --port 2025                   \
      --limit-connections 15       \
      --max-from-ip 5              \
      --user $QPUSER
"
