<body bgcolor="#ffffff" text="#000000" link="#525D76">

<!-- $Id: body-top.inc 1029016 2018-04-26 22:07:22Z sebb $ -->

  <table border="0" cellspacing="0"><!-- table 1 -->
    <!-- TOP IMAGE -->
    <tr>
    <td align="center">
      <a href="http://jmeter.apache.org/"><img src="https://jmeter.apache.org/images/logo.png" alt="Apache JMeter" title="Apache JMeter" border="0"/></a>
    </td>
    </tr>
  </table> <!-- end of table 1 -->
  <table border="0" width="100%" cellspacing="4"> <!-- table 2 -->
    <tr>
      <td colspan="2">
        <hr noshade size="1"/>
      </td>
    </tr>
    <tr>
    <!-- LEFT SIDE NAVIGATION -->
      <td width="20%" valign="top" nowrap="true">
        <p><strong>About</strong></p>
        <ul>
          <li><a href="http://jmeter.apache.org/index.html">Overview</a></li>
          <li><a href="http://jmeter.apache.org/changes.html">Changes</a></li>
          <li><a href="http://jmeter.apache.org/issues.html">Issues</a></li>
          <li><a href="http://www.apache.org/licenses/">License</a></li>
          <li><a href="http://wiki.apache.org/jmeter/JMeterCommitters">Contributors</a></li>
        </ul>

        <p><strong>Download</strong></p>
        <ul>
          <li><a href="http://jmeter.apache.org/download_jmeter.cgi">Download Releases</a></li>
        </ul>

        <p><strong>Documentation</strong></p>
        <ul>
          <li><a href="http://jmeter.apache.org/usermanual/index.html">User Manual</a></li>
          <li><a href="http://jmeter.apache.org/api/index.html">Javadocs</a></li>
          <li><a href="http://jmeter.apache.org/localising/index.html">Localisation (Translator's Guide)</a></li>
          <li><a href="http://jmeter.apache.org/building.html">Building JMeter and Add-Ons</a></li>
          <li><a href="http://wiki.apache.org/jmeter">JMeter Wiki</a></li>
          <li><a href="http://wiki.apache.org/jmeter/JMeterFAQ">FAQ (Wiki)</a></li>
        </ul>

        <p><strong>Tutorials (PDF format)</strong></p>
        <ul>
          <li><a href="http://jmeter.apache.org/usermanual/jmeter_distributed_testing_step_by_step.pdf">Distributed Testing</a></li>
          <li><a href="http://jmeter.apache.org/usermanual/jmeter_proxy_step_by_step.pdf">Recording Tests</a></li>
          <li><a href="http://jmeter.apache.org/usermanual/junitsampler_tutorial.pdf">JUnit Sampler</a></li>
          <li><a href="http://jmeter.apache.org/usermanual/jmeter_accesslog_sampler_step_by_step.pdf">Access Log Sampler</a></li>
          <li><a href="http://jmeter.apache.org/extending/jmeter_tutorial.pdf">Extending JMeter</a></li>
        </ul>

        <p><strong>Community</strong></p>
        <ul>
          <li><a href="http://www.apache.org/foundation/getinvolved.html">Get Involved</a></li>
          <li><a href="http://jmeter.apache.org/mail.html">Mailing Lists</a></li>
          <li><a href="http://jmeter.apache.org/svnindex.html">SVN Repositories</a></li>
        </ul>

        <p><strong>Foundation</strong></p>
        <ul>
          <li><a href="http://www.apache.org/">ASF</a></li>
          <li><a href="http://www.apache.org/foundation/sponsorship.html">Sponsorship</a></li>
          <li><a href="http://www.apache.org/foundation/thanks.html">Thanks</a></li>
        </ul>

      </td>
      <td width="80%" align="left" valign="top">
      <br />

  <table border="0" cellspacing="0" cellpadding="2" width="100%"> <!-- table 3 -->
    <tr>
      <td colspan="5" "bgcolor="#525D76" style="width: 402px; height: 23px;">
      <font color="#ffffff" face="arial,helvetica,sanserif">
      <strong>Nightly builds for developers</strong></font>
      </td>
    </tr>
    <tr>
      <td colspan="5">
      <blockquote>
      <h2>What are the nightly builds?</h2>
        <p>The nightly builds are interim builds that are <b>untested and unsupported</b>.
           <i>Use at your own risk!</i>
           <br />
	     These unreleased builds may not even load, may have undocumented features, 
	     known defects, and any number of other issues.
	   <br />
             They are intended for use by developers and others wishing to help with resolving JMeter bugs.
	</p>
        <p>
          <span style="font-size : x-large">
          <b>These builds should not be used in production.</b>
          </span>
          <h2>Installing JMeter runtime</h2>
             Download a binary archive (i.e. one without a _src suffix) and unpack it
          <h2>Building JMeter</h2>
            Download a source archive (i.e. one with a _src suffix) and unpack it
            <br />
            Run ant download_jars from the top-level directory to fetch the dependencies.
            <br />
        </p>
          <h2>Warning - please note!</h2>
        <p>
          <span style="font-size : large">
            <b>The nightly builds may or may not work properly - or at all.</b>
          </span>
        </p>
        <p>
	  If there is a problem with a particular version, 
          it may be worth reporting this on the JMeter-dev mailing list and/or trying again in a day or two.
        </p>
      </blockquote>
    </p>
